name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      - run: nix build
      - run: nix flake check

  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 45

    strategy:
      matrix:
        preset:
          - gcc_debug
          # Disable gcc_debug_san preset due to an ICE:
          #   internal compiler error: in tree_node, at cp/module.cc:9996
          # - gcc_debug_san
          - gcc_debug_valgrind
          - gcc_release
          # gcc thread sanitizer does not play well with modules either, failing with compiler error:
          #   shared_ptr_atomic.h:421:9: error:
          #   ‘template<class _Tp> std::_Sp_atomic<>::_Atomic_count::~_Atomic_count()’
          #   exposes TU-local entity ‘__tsan_mutex_not_static’
          # - gcc_release_tsan
          - llvm_debug
          - llvm_debug_san
          - llvm_debug_valgrind
          - llvm_release
          - llvm_release_tsan

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache
          key: cache_main_${{ matrix.preset }}_${{ hashFiles('flake.lock') }}
          restore-keys: cache_main_${{ matrix.preset }}

      - name: Configure
        run: cmake -B build --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build build --parallel --verbose
      - name: Test
        run: ctest --test-dir build --parallel --verbose
      - name: Install
        run: cmake --install build --prefix build/install --verbose
      - name: Test install
        if: ${{ !contains(matrix.preset, 'san') }}
        run: |
          cmake -G Ninja -S build/test_install/ -B build/test_install/build \
            -Dcpp_contests_DIR="$(realpath build/install/lib*/cmake/cpp_contests/)"
          cmake --build build/test_install/build --parallel --verbose
      - name: Create package
        run: cd build && cpack -C CPackConfig.cmake

  format:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - uses: cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - name: Configure
        run: cmake -B build --preset gcc_debug
      - name: Check format
        run: |
          cmake --build build --target format
          if [[ -n "$(git diff)" ]]; then
            echo "Code is not formatted. Run: cmake --build build --target format"
            git diff
            exit 1
          fi
