name: Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
      - run: nix build

  test:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        preset:
          - gcc_debug
          - gcc_debug_san
          - gcc_debug_valgrind
          - gcc_release
          - gcc_release_tsan
          - llvm_debug
          - llvm_debug_san
          - llvm_debug_valgrind
          - llvm_release
          - llvm_release_tsan

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31
      - uses: nicknovitski/nix-develop@9be7cfb4b10451d3390a75dc18ad0465bed4932a # v1.2.1
      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache
          key: cache_main_${{ matrix.preset }}_${{ hashFiles('flake.lock') }}
          restore-keys: cache_main_${{ matrix.preset }}

      - name: Configure
        run: cmake -B build --preset ${{ matrix.preset }}
      - name: Build
        run: cmake --build build --parallel --verbose
      - name: Test
        run: ctest --test-dir build --parallel --verbose
      - name: Install
        run: cmake --install build --prefix build/install --verbose
      - name: Test install
        run: |
          cmake -G Ninja -S build/test_install/ -B build/test_install/build \
            -Dcpp_contests_DIR="$(realpath build/install/lib*/cmake/cpp_contests/)"
          cmake --build build/test_install/build --parallel --verbose
      - name: Create package
        run: cd build && cpack -C CPackConfig.cmake

      - name: Check format
        run: |
          cmake --build build --target format
          if [[ -n "$(git diff)" ]]; then echo "Code is not formatted."; git diff; exit 1; fi
